include:
  - path: ../misis-excursion/docker-compose.yml
  - path: ../misis-FriendsM/docker-compose.yml
  - path: ../misis-psy/docker-compose.yml
  - path: ../misis-sigma/docker-compose.yml
#  - path: ../misis-unimates/docker-compose.yml
  - path: ../misis-stuff/docker-compose.yml
  - path: ../misis-dest/docker-compose.yml
  - path: ../misis-cho/docker-compose.yml
  - path: ../misis-sport/docker-compose.yml
  - path: ../misis-nosh/docker-compose.yml
  - path: ../misis-extracts/docker-compose.yml
  - path: ../misis-obsch/docker-compose.yml
  - path: ../misis-inquiry/docker-compose.yml
  - path: ../misis-gravity/docker-compose.yml
  - path: ../misis-tp/docker-compose.yml
  - path: ../misis-tasty/docker-compose.yml
  - path: ../coodfort/docker-compose.yml
services:
  misis-nginx:
    env_file:
      - path: ./nginx/.env
        required: true
    build: ./nginx
    container_name: misis-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    #depends_on:
    #  - misisspace.landing
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - misis-nginx-logs:/var/log/nginx/services/:rw
      - /home/pavel/misis-map/:/usr/share/nginx/map/:ro
  misis-certbot:
    image: certbot/certbot:latest
    container_name: misis-certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  mysql-db:
    image: mysql:latest
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysqldata:/var/lib/mysql
#  backuper:
#    image: lscr.io/linuxserver/syncthing:latest
#    container_name: backuper
#    hostname: backuper #optional
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Etc/UTC
#    volumes:
#      - ./backuper/conf:/config
#      - backup-volume:/bckp/:rw
#    restart: unless-stopped

volumes:
  misis-backup-volume:
    name: misis-backup-volume
  misis-nginx-logs:
    name: misis-nginx-logs
  mysqldata:
    name: mysqldata

networks:
  default:
    name: misis-network