include:
  - path: ../coodfort/docker-compose.yml
  - path: ../dolceforte/docker-compose.yml
services:
  misis-nginx:
    env_file:
      - path: ./nginx/.env
        required: true
    build: ./nginx
    container_name: misis-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - tool
      - api
      - cf-tool
      - cf-api
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - misis-nginx-logs:/var/log/nginx/services/:rw
  misis-certbot:
    image: certbot/certbot:latest
    container_name: misis-certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  mysql-db:
    image: mysql:latest
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: ['mysqld', '--performance-schema=OFF']
    volumes:
      - mysqldata:/var/lib/mysql
#  backuper:
#    image: lscr.io/linuxserver/syncthing:latest
#    container_name: backuper
#    hostname: backuper #optional
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Etc/UTC
#    volumes:
#      - ./backuper/conf:/config
#      - backup-volume:/bckp/:rw
#    restart: unless-stopped

volumes:
  misis-backup-volume:
    name: misis-backup-volume
  misis-nginx-logs:
    name: misis-nginx-logs
  mysqldata:
    name: mysqldata

networks:
  default:
    name: misis-network