include:
  - path: ../dolceforte/docker-compose.yml
services:
  misis-nginx:
    env_file:
      - path: ./nginx/.env
        required: true
    build: ./nginx
    container_name: misis-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - cf-tool
      - cf-api
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - misis-nginx-logs:/var/log/nginx/services/:rw
  misis-certbot:
    image: certbot/certbot:latest
    container_name: misis-certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  mysql-db:
    image: mysql:latest
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: ['mysqld', '--performance-schema=OFF']
    volumes:
      - mysqldata:/var/lib/mysql
#  backuper:
#    image: lscr.io/linuxserver/syncthing:latest
#    container_name: backuper
#    hostname: backuper #optional
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Etc/UTC
#    volumes:
#      - ./backuper/conf:/config
#      - backup-volume:/bckp/:rw
#    restart: unless-stopped
  df-mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: df-mailserver
    hostname: mail
    domainname: dolceforte.rs
    ports:
      - "25:25"    # SMTP
      - "587:587"  # Submission
      - "993:993"  # IMAP
#      - "8080:80"    # HTTP (для Let's Encrypt)
    volumes:
      - ./df-mailserver/docker-data/dms/mail-data/:/var/mail/
      - ./df-mailserver/docker-data/dms/mail-state/:/var/mail-state/
      - ./df-mailserver/docker-data/dms/mail-logs/:/var/log/mail/
      - ./df-mailserver/docker-data/dms/config/:/tmp/docker-mailserver/
      - ./certbot/conf:/etc/letsencrypt:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=0  # Отключить SpamAssassin
      - ENABLE_CLAMAV=0        # Отключить ClamAV
      - ENABLE_FAIL2BAN=1      # Защита от brute-force
      - SSL_TYPE=letsencrypt   # Авто-TLS через Let's Encrypt
      - SSL_DOMAIN=mail.dolceforte.rs
      - PERMIT_DOCKER=host     # Доступ для Docker-сети
    cap_add:
      - NET_ADMIN
    restart: always

volumes:
  misis-backup-volume:
    name: misis-backup-volume
  misis-nginx-logs:
    name: misis-nginx-logs
  mysqldata:
    name: mysqldata

networks:
  default:
    name: misis-network